### ISSUE TITLE
Border color of side nav should be moved to a different file

### ISSUE THREAD

**Issue by kaymckelly** [IACR/conference-template#140]
In styles/jasny-bootstrap.css, this (around line 228): 
`.navmenu-default,
.navbar-default .navbar-offcanvas {
  background-color: #f8f8f8;
  /* NOTE: this is the setting for the right border of the side navbar */
  border-color: #e7e7e7;
  /* NOTE: if using dark side nav bg, try #182A2E  */
}`
sets the color of the right border on the side nav. Users may wish to change it depending on whether they're using a light or dark theme. As such, it should be moved to either main.css or to a theme.

**Comment by kmccurley** [comment]
Side nav is gone in 2.0, so this is irrelevant.
