### ISSUE TITLE
program.json etc is cached by browser

### ISSUE THREAD

**Issue by kmccurley** [IACR/conference-template#147]
Reported by Fabrice: "A small caching issue on the IACR server: The html pages themselves are served with the header “Cache-control: no-cache” but not the JS/CSS/JSON/fragments, which means they are not updated if the cache of the browser is not emptied. This usually means that to see changes on the menu and the program for example, we need to clear the cache (for Chrome/Firefox, Command+Shift+R on Mac, Shift+F5 on Linux/Windows). I've tried to write a .htaccess fixing this but I did not manage as the module mod_headers is not loaded."

I can think of several possible solutions:
1. modify the sever configuration to set Cache-control: no-cache on every request.
2. load the module that Fabrice mentioned. This would unfortunately require a .htaccess to always be present.
3. make the client request program.json?id=random_number so that it would look like a new request.

I'm inclined to go with the first one, but it could break in the future.

**Comment by kmccurley** [comment]
This was triggered in the asiacrypt 2018 installation and needs to be fixed. It's possible to replace the $.getJSON calls with raw $.ajax calls in jquery, and set the cache: option to false so that the requests are not fetched from cache. This is probably better than modifying the global setting on s3.

**Comment by kaymckelly** [comment]
Partial fix with a6caa0a1a6b67951d43a06e04ad4ff70a7c154f0

**Comment by kaymckelly** [comment]
Rest of the fix with 5b51d81479e61a18389f281493d5a4646f1ef183
