### ISSUE TITLE
Default content should be omitted

### ISSUE THREAD

**Issue by kmccurley** [IACR/conference-template#152]
Apparently it is too easy for a conference webmaster to overlook the default content that is provided with the IACR conference template. See https://twitter.com/fakeiacr/status/1029128135776890883?lang=en

**Comment by kaymckelly** [comment]
This will be addressed with updates to the installation docs ( with #130) and hopefully made a bit simpler.

**Comment by kmccurley** [comment]
This is mostly fixed with the .editMe class.
