### ISSUE TITLE
Show individual talk times

### ISSUE THREAD

**Issue by kmccurley** [IACR/conference-template#154]
Kenny Paterson has requested that individual talks for RWC should show the start and end time for the talks. In the case of a single-session timeslot, this is possible to implement using a position: absolute hanging off the left of the individual talk (the added element has a red background for clarity in this discussion).
![rwcprogram1](https://user-images.githubusercontent.com/14105363/49758000-9faa2780-fc72-11e8-9c2d-ec091110a152.png)

This also works in dual session timeslots when in mobile mode, but it's problematic with dual sessions in desktop mode because the two talks alongside each other could have different start and end times. The simple solution for this case is to put the talk time underneath the title.
![rwcprogram2](https://user-images.githubusercontent.com/14105363/49758174-2c54e580-fc73-11e8-835a-9dd1fe2ff4c7.png)

**Comment by kaymckelly** [comment]
I move to categorize this as "won't fix"; only RWC really uses this.
