### ISSUE TITLE
Date parsing is wrong in javascript

### ISSUE THREAD

**Issue by kmccurley** [IACR/conference-template#155]
The change to display the day of the week resulted in displaying the WRONG date. This is a critical bug since we display the wrong day of the week and wrong date on the program. The fix for the helper in program.js is as follows:
`Handlebars.registerHelper('formatDate', function(isodate) {
            var parts = isodate.split('-');
            return new Date(parts[0], parts[1] -1, parts[2]).toLocaleString('en-US', {weekday: "long", month: "short"\
, day: "numeric"});
`

**Comment by kmccurley** [comment]
See https://stackoverflow.com/questions/2587345/why-does-date-parse-give-incorrect-results

**Comment by kaymckelly** [comment]
Fixed
