### ISSUE TITLE
RWC tweaks

### ISSUE THREAD

**Issue by NigelSmart** [IACR/conference-template#157]
A couple of things to tweak which would make it easier for RWC next year...

a) For talks we have authors and speakers. So an optional speaker field would be good for those conferences for whom the speaker is important

b) We have a non-standard navigation system for the site (top left panel is general RWC stuff, bottom left is current conference). With some symlinks in the file store to allow easy linking/non duplication of stuff etc. Am not sure how pulling a new version would break our structure here. Some advice on how to spawn a new conference which does not break our existing conferences would be good.

**Comment by kmccurley** [comment]
a) this is a useful feature that can be added in the program editor and the program template. The program editor will probably be changed to have a separate <input> for each author, and at that time we can add a checkbox to say if they are a speaker.
b) the migration from the bootstrap 3 version to the bootstrap 4 version will break everything anyway. 😂 I like how RWC carries forward the logos for the sponsors using a common directory for each year. The best we can probably do is to update the documentation in the "Advanced topics" section to say how to preserve the previous structure.

**Comment by kmccurley** [comment]
Probably not relevant any more. Meh.
