### ISSUE TITLE
Code of conduct page in left nav

### ISSUE THREAD

**Issue by kmccurley** [IACR/conference-template#160]
IACR has adopted a code of conduct for conferences that needs to appear in the left nav as a separate page.

**Comment by kmccurley** [comment]
The way the general chair guidelines are written, it is impossible to create a single page that will work for all of the conferences. We could substitute the ***and others relevant to event*** with a link to the contact.html page with anchor text that says "the general chair". I frankly have no idea what should go in place of ***subject to applicable laws*** - not even in the country/state/city I live in.

**Comment by kaymckelly** [comment]
Resolved via pull request e53984a65a600663d2147510917ff2ba8fb8611b
