### ISSUE TITLE
Need more deadlines

### ISSUE THREAD

**Issue by kmccurley** [IACR/conference-template#163]
The Eurocrypt 2020 site did not use the deadlines in metadata.json, perhaps because they didn't know at the time the site was set up, but also because they have [multiple deadline](https://eurocrypt.iacr.org/2020/callforpapers.html).

**Comment by kaymckelly** [comment]
We could have empty dates in metadata.json that can be supplied later. If the string is empty, the date would not display.

**Comment by kaymckelly** [comment]
Also check that expired dates have strikethrough.

**Comment by kmccurley** [comment]
The new version has all dates in a single place, so this is outdated.
