### ISSUE TITLE
menus.js escapes html comment in title

### ISSUE THREAD

**Issue by kaymckelly** [IACR/conference-template#166]

**Comment by kaymckelly** [comment]
Reported by @cryptojedi

**Comment by kmccurley** [comment]
It's strange that we never noticed this before. I fixed it by changing the line in menus.js to read:
document.title = data.shortName;
without preserving the existing title. We'll have to fold this in when we rewrite the template.

**Comment by kmccurley** [comment]
We no longer use menus.js, so this is out of date.
