### ISSUE TITLE
foreach fails in currentProgram.php

### ISSUE THREAD

**Issue by kmccurley** [IACR/conference-template#187]
php 7 made an incompatible change at some point with regard to modifying a php object inside a loop. This works on php 7.0.33 but fails on Kay's 7.4.2.

**Comment by kaymckelly** [comment]
Error message: Invalid argument supplied for foreach() in <b>/Users/Somorros/Geek/virtual-conference/currentProgram.php</b> on line <b>15</b>

**Comment by kmccurley** [comment]
I am unable to recreate this, and php 7.4 is not available for linux through standard distribution channels. We can either test this further on the mac, or revert your mac to php 7.2, or you can work on your linux machine. We should also do a var_dump($editorData) before the first foreach()

**Comment by kmccurley** [comment]
s3 is now running php 7.4, but currentProgram.php is not yet part of the repository.

**Comment by kaymckelly** [comment]
I believe this is fixed
