### ISSUE TITLE
Need a "role" attribute in comm.json

### ISSUE THREAD

**Issue by kmccurley** [IACR/conference-template#231]
The comm.json file is currently just a list of members of the program committee, but we should start distinguishing people by their role, including things like:
1. program chairs (currently listed in the separate `metadata.json` file).
2. general chairs (currently listed in the separate `metadata.json` file).
3. area chairs (not listed anywhere right now).
4. local arrangements (used by conferences, but not journals)
5. Contributed talks Chair (used by RWC)
6. Invited talks Chair (used by RWC)
7. sponsorship chair (used by RWC)
8. scholarship secretary (used by RWC)
9. managing editor (used by ToSC and TCHES, but not conferences)
10. steering committee (used by area conferences)

Because of the diversity of roles, we might be tempted to use role="free text", but this causes problems in downstream processing. I use these to populate cryptodb where the roles are currently limited by an enum('pc chair', 'general chair', 'pc') but that is not enough. Whenever possible we should stick to standard entries so that we can recognize PC chairs and editor-in-chief positions. General chair positions are sometimes important because they signify membership on the IACR board. For this reason I suggest using a fairly rich enum that we may adapt over time. Note that if a person has multiple roles, then they can be listed multiple times in the file. The things that display it (e.g., the template and cryptodb) can make decisions about how to process the list.

Note that this also requires changes to [the tool used to create the files](https://www.iacr.org/cryptodb/pc/).

**Comment by kaymckelly** [comment]
Specifically, the area chairs should be listed on the cfp and the artifact chair(s) should be listed on cfp and contacts

**Comment by kaymckelly** [comment]
Did it slightly differently but this is addressed in #234
