### ISSUE TITLE
Printable program styled similarly to website

### ISSUE THREAD

**Issue by kaymckelly** [IACR/conference-template#56]
From Mike: "Another thing to consider: there should be a print style-sheet as well. Probably it should look like the full-screen mockup in terms of layout, but without extra shading and without the navigation bar and header etc."

**Comment by kaymckelly** [comment]
We actually added the ability to download a pdf from the program editor. The output is formatted differently from the website though, so it's a partial fulfillment of this request.

**Comment by kmccurley** [comment]
Not a requirement. Who uses paper any more?
